### ISSUE TITLE
Specify build requirements in pyproject.toml's build-system (PEP517)

### ISSUE THREAD

**Issue by pawamoy** [facebookresearch/fastText#1223]
Instead of asking users to pre-install NumPy & SciPy and pybind11 before `pip install`ing fastText, maybe you could specify these build requirements in a `pyproject.toml` file, following the PEP517 spec?

```toml
[build-system]
requires = ["setuptools", "wheel", "numpy", "scipy", "pybind11"]
build-backend = "setuptools.build_meta"
```

This would also allow you to get rid of these brittle/hackish setup instructions:

```python
class get_pybind_include(object):
    def __init__(self, user=False):
        try:
            import pybind11
        except ImportError:
            if subprocess.call([sys.executable, '-m', 'pip', 'install', 'pybind11']):
                raise RuntimeError('pybind11 install failed.')
```

https://setuptools.readthedocs.io/en/latest/build_meta.html#build-system-support
